### ISSUE TITLE
Issues with `useBeforeUnload` on iOS Safari

### ISSUE THREAD

**Issue by marhaupe** [epicweb-dev/restore-scroll#7]
I've been noticing that `ElementScrollRestoration` does not work on iOS Safari, or at least not reliably. I could pinpoint the issue to `useBeforeUnload` not being triggered due to `window.onbeforeunload` not being supported. There have been similar reports for `react-router-dom` (https://github.com/remix-run/react-router/issues/9463), which have been fixed by switching to listening to `window.pagehide` (https://github.com/remix-run/react-router/pull/9945). Monkey patching or rather just forking `ElementScrollRestoration` and adding and using the `usePageHide` hook fixes these problems for me. If this is a known bug that does not only affect me for some reason, I'd be happy to help out with a pull request.

**Comment by kentcdodds** [comment]
I'm fine with switching to a hook like that provided it works for other browsers still. Thanks!

**Comment by marhaupe** [comment]
Knowing you're also involved in the react-router / remix projects, would you prefer to push for `usePageHide` being exported (it currently isn't: https://github.com/remix-run/react-router/blob/7759e8e2912eb69f6dd63b2906490831a2154cfd/packages/react-router-dom/index.tsx#L1919) or would you rather inline the hook?

**Comment by kentcdodds** [comment]
We'll see what the team says! https://x.com/kentcdodds/status/1792931607537467871

**Comment by kentcdodds** [comment]
Team's not keen on exposing that hook (for good reasons) so I just switched to a simple `useEffect` in a couple lines.

**Comment by marhaupe** [comment]
I see, I remember reading a PR comment but I guess the decision wasn't made public. Totally makes sense though, thanks for the quick fix! Appreciate your work a lot.
